name: "PR: Test"

on: #trigger
  pull_request:
    types: [opened, synchronize, reopened] #Eventos disponiveis na documentação

jobs:
  tests: # nome/identificador do job pode ser usado como input
    runs-on: ubuntu-latest #maquina virtual disponibilizada pelo gitHub
    steps: #conjunto de actions que serão realizados
      - uses: actions/setup-node@v2 #instala o node na maquina Ubuntu
      - uses: actions/checkout@v2 # usa o checkout para acessar oc codigo na maquina virtual
      - name: Install dependencies
        run: yarn install
      - run: yarn test
      - name: Harman's Code Coverage Report
        uses: hrgui/lcov-reporter-action@v0.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

# Verificar o MArketPlace de actions => - uses: <autor>/<action>@<version>